# 
# Include cfg.pre.inc to pull in variable and other definitions.
#
PRJ_ROOT=../..
CUR_PATH=hal/x86

include $(PRJ_ROOT)/conf/bld.sys.init.mk

BLD_TARGETS=\
	ldr\

include $(CONF_ROOT)/bld.env.dir.mk

