# 
# Include cfg.pre.inc to pull in variable and other definitions.
#
PRJ_ROOT=./../../
CMP_PATH=./boot/x86/

include $(PRJ_ROOT)/cfg/cfg.pre.mk

TARGET_TYPE=nop

TARGET_LIST=\
	nop

# 
# Execute the data configured above according to standard build system rules.
#
include $(PRJ_ROOT)/cfg/cfg.post.mk

