# 
# Include cfg.pre.inc to pull in variable and other definitions.
#
PRJ_ROOT=../..
CMP_PATH=boot/dbg

include $(PRJ_ROOT)/conf/bld.sys.init.mk

BLD_TARGETS=

# 
# Execute the data configured above according to standard build system rules.
#
include $(CONF_ROOT)/bld.env.nop.mk

