# 
# Include cfg.pre.inc to pull in variable and other definitions.
#
PRJ_ROOT=../..
CMP_PATH=boot/dbg

include $(PRJ_ROOT)/conf/cfg.pre.mk

TARGET_TYPE=dir

TARGET_LIST=\
	app\


# 
# Execute the data configured above according to standard build system rules.
#
include $(PRJ_ROOT)/cfg/cfg.post.mk

