# 
# Include cfg.pre.inc to pull in variable and other definitions.
#
PRJ_ROOT=..
CUR_PATH=boot

include $(PRJ_ROOT)/conf/bld.sys.init.mk

BLD_TYPE=dir

BLD_TARGETS=\
    dbg\
    x86\

# 
# Execute the data configured above according to standard build system rules.
#
include $(CONF_ROOT)/bld.sys.post.mk

